---
title: "STAR Models"
# author: "Logan Stundal"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  bookdown::pdf_document2:
    keep_tex: no
    fig_caption: yes
    number_sections: no
    toc: no
    latex_engine: pdflatex
    citation_package: natbib
header-includes:
  - \usepackage{graphics}
  - \usepackage{pdflscape}
  - \usepackage{booktabs}
  - \usepackage{rotating}
  - \usepackage{threeparttable}
  - \usepackage{dcolumn}
  - \usepackage[bottom, hang]{footmisc}
bibliography: c:/users/logan/googledrive/umn/research/references/library.bib
biblio-style: c:/users/logan/googledrive/umn/research/references/csl-formats/apsrnourl
fontsize: 12pt
---



<!---------------------------------------------------------------------------->



```{r setup, include=FALSE}
knitr::opts_chunk$set(cache      = FALSE,
                      echo       = FALSE,
                      out.width  = "100%",
                      dpi        = 350)

# STAR Models
load("../../Data/Oxford_HB_2021_APSA-Models-Discrete.Rdata")

library(kableExtra)
library(magrittr)
library(texreg)
library(spatialreg)
```



<!---------------------------------------------------------------------------->
## Lagrange Multiplier Tests
<!---------------------------------------------------------------------------->

```{r}

footnote = "Robust Lagrange multiplier tests. P-values in parentheses."

kbl(x         = lagrange2,
    caption   = "Lagrange Multiplier Tests",
    escape    = TRUE,
    col.names = linebreak(c("","", "SIGACT", "ICEWS", "GED"),
                          align = "c"),
    align     = c("l","l","c","c","c"),
    position  = "!ht",
    booktabs  = TRUE) %>%
  kable_styling(font_size = 10) %>% 
  column_spec(column = 1:2, width = "1in") %>% 
  collapse_rows(columns     = 1:2,
                valign      = "middle",
                latex_hline = "none") %>% 
  row_spec(04,  extra_latex_after = "\\cline{1-5}") %>%
  footnote(general = footnote, footnote_as_chunk = T)
```

<!---------------------------------------------------------------------------->



<!---------------------------------------------------------------------------->
## Time-lag (naive) Regression Models
<!---------------------------------------------------------------------------->

```{r results = "asis", fig.pos = "!ht"}
knitreg(l = c(mods_linear_hy, mods_linear_mo),
        custom.coef.map = names_linear,
        include.rsquared = F,
        include.adjrs    = F,
        caption.above      = TRUE,
        caption            = "Time Lag Models",
        custom.header      = list("Half-year" = 1:3, "Month" = 4:6),
        custom.note        = paste0("\n\\item %stars.",
                                    "\\item Phi - temporal lag"),
        threeparttable     = TRUE,
        dcolumn            = TRUE,
        float.pos          = "!ht",
        table              = TRUE,
        booktabs           = TRUE,
        center             = TRUE,
        no.margin          = TRUE,
        fontsize           = "small")
```

<!---------------------------------------------------------------------------->
## Spatial Regression Models
<!---------------------------------------------------------------------------->

```{r results = "asis", fig.pos = "!ht"}
knitreg(l = c(mods_spatial_hy_tidy, mods_spatial_mo_tidy),
        custom.coef.map = names_spatial,
        include.rsquared = F,
        include.adjrs    = F,
        caption.above      = TRUE,
        caption            = "Spatio-Temporal Models",
        custom.header      = list("Half-year" = 1:3, "Month" = 4:6),
        custom.note        = paste0("\n\\item %stars.",
                                    "\\item Rho - spatial lag",
                                    "\\item Phi - temporal lag"),
        threeparttable     = TRUE,
        dcolumn            = TRUE,
        float.pos          = "!ht",
        table              = TRUE,
        booktabs           = TRUE,
        center             = TRUE,
        no.margin          = TRUE,
        fontsize           = "small")
```

<!---------------------------------------------------------------------------->
